#https://blog.csdn.net/u011659172/article/details/50599451
server:
  port: 80
  servlet:
    context-path: /
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      #?useUnicode=true&characterEncoding=UTF-8 解决orm中文入库乱码
      url: jdbc:mysql://182.92.218.84:3306/fpog?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: sawelly
      #使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    freemarker:
      cache: false
      request-context-attribute: request
      suffix: .ftl
      template-loader-path: classpath:/templates/
      settings:
        template_update_delay: 0
        default_encoding: UTF-8
        locale: zh_CN
        number_format: #.##
        datetime_format: yyyy-MM-dd HH:mm:ss
        classic_compatible: true
        template_exception_handler: ignore
    http:
      encoding:
        force: true
    profiles:
      active: @profileActive@




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sawelly.fpog.entity
#  config-location: classpath:mybatis-config.xml
#  check-config-location: true


#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
#输出日志
debug: true